name: client

# 언제 job을 작동시킬지
on: [push, pull_request]

# 어떤 job을 할지
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: client
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Checkout source code.
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        run: npm test
        working-directory: ./
