name: client

# 언제 job을 작동시킬지
on: [push, pull_request]

# 어떤 job을 할지
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: npm install
        working-directory: ./
      - name: Build
        run: npm run build
        working-directory: ./